// server.js

// set up ======================================================================
// set up express
var express  = require('express');
var app      = express();
var port     = process.env.PORT || 8080;

// gather all the modules
var bodyParser      = require('body-parser');
var cookieParser    = require('cookie-parser');
var fs              = require('fs');
var helmet          = require('helmet');
var morgan          = require('morgan');
var passport        = require('passport');
var session         = require('express-session');


// import other files
var passportConfig  = require('./config/passport'); // config file with all the passport content
var cert = fs.readFileSync('./cert/wso2/cert.pem', 'utf8'); // this validates the response coming back (got from WSO2 metadata file)
var privateCert = fs.readFileSync('./cert/generated/key.pem', 'utf8'); // this signs the response being sent (generated by you)
var decryptionPvk = fs.readFileSync('./cert/generated/key.pem', 'utf8'); // this is to decrypt the assertion (not encrypting it on WSO2 rn due to a pending JCE update)

var nodeProfile = null; // variable to store node profile

// set up the modules
app.use(helmet()); // set helmet on for security
app.use(morgan('dev')); // log every request to the console in "dev" mode

// allow app to get information from html forms
app.use(bodyParser.urlencoded({
  extended: true
}));
app.use(cookieParser());

// session security stuff
app.use(session({
    secret: passportConfig.SESSION_SECRET,
    name: 'sessionId',
    resave: true,
    saveUninitialized: true,
    cookie: {
        httpOnly: true,
        maxAge: 30 * 60 * 1000 // 30 minutes
    },
    rolling: true
}));

// directory with content to display on webapp
app.use(express.static(__dirname + '/public'));

// configure passport ==========================================================
var SamlStrategy = require('passport-saml').Strategy;

passport.serializeUser(function (user, done) {
    done(null, user);
});

passport.deserializeUser(function (user, done) {
    done(null, user);
});

var samlStrategy = new SamlStrategy({
    path: passportConfig.PATH, // the callback path
    protocol: 'http://',
    entryPoint: passportConfig.ENTRY_POINT, // the sso path
    issuer: passportConfig.ISSUER, // the SP's SAML issuer name
    audience: passportConfig.AUDIENCE, // the audience expected in the SAML response, wip
    cert: cert, // if this cert is present it will use it to validate the SAML response that comes back
    privateCert: privateCert, // this cert is use to sign the SAML AuthN request thats going to WSO2
    //decryptionPvk: decryptionPvk, // this is the key used to decrypt the assertion coming back, not used rn
    identifierFormat: passportConfig.NAME_ID_FORMAT, // NameID format
    attributeConsumingServiceIndex: passportConfig.ACS_INDEX, // ACS ID
    logoutUrl: passportConfig.LOGOUT_URL, // SLO url
    validateInResponseTo: true
}, function(profile, done) {
    nodeProfile = profile;
    console.log('Profile: ' +  JSON.stringify(nodeProfile, null, 4));
    return done(null, profile);
});

passport.use(samlStrategy);

app.use(passport.initialize());
app.use(passport.session());

// launch ======================================================================
app.listen(port);
console.log('Welcome to the SAML app on port ' + port);

// routes ======================================================================
require('./app/routes.js')(app, passport, samlStrategy, cert); // load our routes and pass in our app and fully configured passport